#!/bin/bash

BASEPATH=`dirname "$0"`

if [ ! -e .init-done ]
then
	echo -en "Initializing IPFS daemon..."
	src/init/init.sh 2>&1 >> /dev/null
	echo " done"
else
	echo -en "Cleaning up IPFS..."
	src/init/clean.sh 2>&1 >> /dev/null
	echo " done"
fi

source $BASEPATH/config

python3 src/do.py -a $ADDRESS -k $PRIVATE_KEY $@
