#!/bin/bash
BASEPATH=`dirname "$0"`
LOCAL=False
while getopts "f:s:a:k:c:m:d:b:t:n:i:rl" option;
do
case "${option}" in
            l)
                    LOCAL=True;;

    esac
done


echo "$LOCAL"

if [ ! -e .init-done ]
then
	echo "$0 was not initialized yet"
	echo "Requirements fot the $0 are the following:
1. ipfs daemon running and listening on localhost:5000
2. python3 with pip
3. ipfshttpclient python module
4. web3 python module"
        while [ 1 == 1 ]
	do
		echo -en "Proceed with automated initalization [Y/n]: "
		read -r RESPONSE

		case $RESPONSE in
		"")
			echo -en "Initializing... "
			if [ "$LOCAL" == True ]
			then
	 			src/init/init.sh -l 2>&1 >> /dev/null
	 		else
	 			src/init/init_python.sh 2>&1 >> /dev/null
			fi
		        break
		        ;;
		y)
			echo -en "Initializing... "
			if [ "$LOCAL" == True ]
			then
	 			src/init/init.sh -l 2>&1 >> /dev/null
	 		else
	 			src/init/init_python.sh 2>&1 >> /dev/null
			fi
			INIT=$?
			break
			;;
		n)
			exit
			;;
		*)
			echo "Please specify 'y' or 'n' for yes or no."
			continue
			;;
		esac
	done

	case "$INIT" in
        1)
		echo "failed"
		echo "$0 requires python3 installed. Please install it using your system's package manager"
		exit
		;;
        2)
	        echo "failed"
                echo "$0 requires python3-pip installed.  Please install it using your system's package manager."
                exit
                ;;
        0)
		echo "done"
            	;;
        *)
	esac

else
	echo -en "Cleaning up IPFS..."
	src/init/clean.sh 2>&1 >> /dev/null
	echo " done"
fi

source "${BASEPATH}/config"

if [ "$OS" == "Windows_NT" ]
then
	PYTHON_BIN="python"
else
	PYTHON_BIN="python3"
fi
echo "${PYTHON_BIN}"
${PYTHON_BIN} src/do.py -a $ADDRESS -k $PRIVATE_KEY $@
